### ISSUE TITLE
SDK resolution cannot find other versions

### ISSUE THREAD

**Issue by dyskette** [flathub/org.freedesktop.Sdk.Extension.dotnet6#16]
`dotnet` is designed to resolve all the SDK installed versions under `DOTNET_ROOT` or /etc/dotnet/install_location. However, because these extensions install the files under different paths, `dotnet` cannot resolve other versions, and only one version can be used at any time.

https://docs.microsoft.com/en-us/dotnet/core/distribution-packaging
https://github.com/dotnet/designs/blob/main/accepted/2020/install-locations.md
https://github.com/dotnet/designs/blob/main/accepted/2021/install-location-per-architecture.md

There are instances where different SDKs are used with multiple project associated to the same solution (.sln) file. Building those solutions with the current extensions is not possible.

**Comment by patriziobruno** [comment]
I'm not sure I understand the use case. You can target any mix of .NET frameworks using the latest SDK. Why do you need older SDKs?

Unfortunately, the fact that `dotnet` installations mix different SDK versions under the same root, makes this scenario incompatible with Flatpak runtime extensions. The only solution I see would be to have one big package containing all the available SDKs and I'm not sure what kind of advantage you'd get.

Alternatively, you can install `dotnet` directly from Microsoft's packages into your user's home (or another host dir) and make that directory available to your Flatpaks using the `--filesystem` CLI flag or [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) if you don't want to use the cmdline.

**Comment by dyskette** [comment]
Right. It's been a while but I remember having issues trying to compile/run older projects using .NET 6. Anyhow, there are alternatives, so it's not an issue for me anymore.
