### ISSUE TITLE
Add extension for 23.08

### ISSUE THREAD

**Issue by NorbiPeti** [flathub/org.freedesktop.Sdk.Extension.dotnet6#54]
The situation is similar to #25. I'm trying to use Rider with dotnet6 but it recently got updated to 23.08 so I can't use this extension.

.NET 6 is LTS so I would rather stay on this version.

**Comment by horas13** [comment]
Any chance this gets addressed? It blocks all applications using the extensions from switching to the 23.08 runtime.
